AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Práctica intermodular serverless
Transform:
- AWS::Serverless-2016-10-31

Resources:
  # Función Lambda para obtener las notas de un usuario
  getNotes:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/getNotes.handler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 5
      Description: Función para leer las notas de la tabla
      Policies:
        # Política de permisos para interactuar con la tabla de DynamoDB. Permisos CRUD.
        - DynamoDBCrudPolicy:
            TableName: !Ref AppTable
      Environment:
        Variables:
          # Referencia al nombre de la tabla a través de una variable de entorno
          APP_TABLE: !Ref AppTable

  # Función Lambda para crear una nota para un usuario
  postNotes:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/postNotes.handler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 5
      Description: Función para crear una nota en la tabla
      Policies:
        # Política de permisos para interactuar con la tabla de DynamoDB. Permisos CRUD.
        - DynamoDBCrudPolicy:
            TableName: !Ref AppTable
      Environment:
        Variables:
          # Referencia al nombre de la tabla a través de una variable de entorno
          APP_TABLE: !Ref AppTable

  # Función Lambda para obtener una nota específica
  getNote:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/getNote.handler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 5
      Description: Función para obtener una nota específica
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AppTable
      Environment:
        Variables:
          APP_TABLE: !Ref AppTable

  # Función Lambda para actualizar una nota
  putNote:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/putNote.handler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 5
      Description: Función para actualizar una nota
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AppTable
      Environment:
        Variables:
          APP_TABLE: !Ref AppTable

  # Función Lambda para eliminar una nota
  deleteNote:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/deleteNote.handler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 5
      Description: Función para eliminar una nota
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AppTable
      Environment:
        Variables:
          APP_TABLE: !Ref AppTable

  # Función Lambda para procesar una nota
  processNote:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/processNote.handler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      MemorySize: 256
      Timeout: 30
      Description: Función para procesar una nota (audio y traducción)
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AppTable
        - Statement:
            - Effect: Allow
              Action:
                - polly:SynthesizeSpeech
              Resource: "*"
            - Effect: Allow
              Action:
                - translate:TranslateText
              Resource: "*"
            - Effect: Allow
              Action:
                - comprehend:DetectDominantLanguage
              Resource: "*"
            - Effect: Allow
              Action:
                - s3:PutObject
                - s3:GetObject
              Resource: !Sub "arn:aws:s3:::${AppBucket}/*"
      Environment:
        Variables:
          APP_TABLE: !Ref AppTable
          APP_S3: !Ref AppBucket

  # TODO: Añadir las funciones que faltan a continuación




  # Tabla DynamoDB
  # Observa que no vamos a utilizar el recurso AWS::Serverless::SimpleTable, porque
  # solo deja definir clave de partición y no clave de ordenación
  # Por tanto, incluimos un recurso AWS::DynamoDB::Table de CloudFormation
  # Puedes comprobar por tanto que en plantillas SAM se pueden incluir también recursos
  # de CloudFormation
  AppTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: userId # Si lo deseas, puedes cambiar el nombre de las claves. Recuerda actualizar el código también
          AttributeType: S
        - AttributeName: noteId # Si lo deseas, puedes cambiar el nombre de las claves. Recuerda actualizar el código también
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: noteId
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

  # Bucket S3 para almacenar archivos de audio
  AppBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-audio-bucket-${AWS::AccountId}"

# Salidas para mostrar el nombre de las funciones que se han creado
Outputs:
  getNotesFunctionName:
    Value: !Ref getNotes
  postNotesFunctionName:
    Value: !Ref postNotes
  getNoteFunctionName:
    Value: !Ref getNote
  putNoteFunctionName:
    Value: !Ref putNote
  deleteNoteFunctionName:
    Value: !Ref deleteNote
  processNoteFunctionName:
    Value: !Ref processNote
  AppBucketName:
    Value: !Ref AppBucket
