AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Práctica intermodular serverless - Frontend incluido

Transform:
  - AWS::Serverless-2016-10-31

Parameters:
  FrontendBucketName:
    Type: String
    Description: Nombre único global para el bucket del frontend (ej. notas-tus-iniciales). Si se deja vacío, se generará automáticamente.
    Default: ""

Conditions:
  # Condición para usar el nombre personalizado solo si se proporcionó
  HasBucketName: !Not [!Equals [!Ref FrontendBucketName, ""]]

Resources:

  # API Gateway explícito para CORS
  NotesApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization,X-Amz-Date,X-Api-Key'"
        AllowOrigin: "'*'"

  # Tabla DynamoDB
  AppTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: noteId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: noteId
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

  # Bucket S3 para almacenar audios (privado)
  AppBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-notes-bucket"

  # Bucket S3 para el frontend (público, sitio web estático)
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !If
        - HasBucketName
        - !Ref FrontendBucketName
        - !Sub "notas-${AWS::AccountId}-frontend"
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  # Política del bucket frontend para acceso público de lectura
  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource: !Sub "${FrontendBucket.Arn}/*"

  # Funciones Lambda (se mantienen exactamente igual que en tu plantilla original)
  getNotes:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/getNotes.handler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 5
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AppTable
      Environment:
        Variables:
          APP_TABLE: !Ref AppTable
      Events:
        GetNotesApi:
          Type: Api
          Properties:
            RestApiId: !Ref NotesApi
            Path: /notes
            Method: get

  postNotes:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/postNotes.handler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 5
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AppTable
      Environment:
        Variables:
          APP_TABLE: !Ref AppTable
      Events:
        PostNotesApi:
          Type: Api
          Properties:
            RestApiId: !Ref NotesApi
            Path: /notes
            Method: post

  getNote:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/getNote.handler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 5
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AppTable
      Environment:
        Variables:
          APP_TABLE: !Ref AppTable
      Events:
        GetNoteApi:
          Type: Api
          Properties:
            RestApiId: !Ref NotesApi
            Path: /notes/{noteId}
            Method: get

  deleteNote:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/deleteNote.handler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 5
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AppTable
      Environment:
        Variables:
          APP_TABLE: !Ref AppTable
      Events:
        DeleteNoteApi:
          Type: Api
          Properties:
            RestApiId: !Ref NotesApi
            Path: /notes/{noteId}
            Method: delete

  putNote:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/putNote.handler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 5
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AppTable
      Environment:
        Variables:
          APP_TABLE: !Ref AppTable
      Events:
        PutNoteApi:
          Type: Api
          Properties:
            RestApiId: !Ref NotesApi
            Path: /notes/{noteId}
            Method: put

  processNote:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/processNote.handler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      MemorySize: 256
      Timeout: 10
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AppTable
        - S3CrudPolicy:
            BucketName: !Ref AppBucket
        - Statement:
            Effect: Allow
            Action:
              - translate:TranslateText
              - polly:SynthesizeSpeech
            Resource: "*"
      Environment:
        Variables:
          APP_TABLE: !Ref AppTable
          APP_BUCKET: !Ref AppBucket
      Events:
        ProcessNoteApi:
          Type: Api
          Properties:
            RestApiId: !Ref NotesApi
            Path: /notes/{noteId}/process
            Method: post

# Outputs
Outputs:
  getNotesFunctionName:
    Value: !Ref getNotes
  postNotesFunctionName:
    Value: !Ref postNotes
  getNoteFunctionName:
    Value: !Ref getNote
  deleteNoteFunctionName:
    Value: !Ref deleteNote
  putNoteFunctionName:
    Value: !Ref putNote
  processNoteFunctionName:
    Value: !Ref processNote
  AppTableName:
    Value: !Ref AppTable
  AppBucketName:
    Value: !Ref AppBucket
  NotesApiUrl:
    Value: !Sub "https://${NotesApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
    Description: URL del API Gateway
  FrontendBucketName:
    Value: !Ref FrontendBucket
    Description: Nombre del bucket para el frontend (subir aquí los archivos estáticos)
  FrontendWebsiteURL:
    Value: !GetAtt FrontendBucket.WebsiteURL
    Description: URL pública del sitio web estático 